#!/bin/sh
function podconflict () {
    if [ -f "./Podfile" ]; then
        # first add podfile
        git add Podfile
        conflict_list=`git diff --name-only --diff-filter=U | sed 's/[[:space:]]/_-_/g' | tr "\n" "^"`
        result=$(echo $conflict_list | grep "Podfile^")

        if [[ "$result" != "" ]];then
            echo "Podfile conflict, please resolve it first and then execute pod add Podfile"
        else
            git checkout Pods/Manifest.lock --ours
            git checkout Pod* --ours
            pod install
            git add Pod*
        fi
    fi
}

function podcreate () {
    ruby $HOME/SimpleUtilTools/pod/podcreate.rb `pwd` $1
}

function podcreatedummy () {
    ruby $HOME/SimpleUtilTools/pod/podcreatedummy.rb `pwd` $1
}