#!/bin/sh
function update_tools() {
    folder=`pwd`
    cd $HOME
    if [[ ! -d "SimpleUtilTools" ]];
    then
        git clone git@github.com:foobra/SimpleUtilTools.git
    fi
    cd SimpleUtilTools && git pull
    cd $folder
}
