#!/bin/sh
function update_tools() {
    folder=`pwd`
    cd $HOME/SimpleUtilTools && git pull
    cd $folder
    source ~/.zshrc
    source ~/.profile
    source ~/.bash_profile
    source ~/.bashrc
}
