#!/bin/sh
function update_tools() {
    folder=`pwd`
    cd $HOME/SimpleUtilTools && git pull
    cd $folder
    source ~/.zshrc || true
    source ~/.profile || true
    source ~/.bash_profile || true
    source ~/.bashrc || true
}
